dcu_serial_no: 45778
prefix_id: ABCCFF
cluster_id: 1
network_id: RF
mqtt_hostname: mqtt.eclipseprojects.io
mqtt_username: None
mqtt_password: None
mqtt_port: 1883
mqtt_force_unsecure: true
mqtt_rate_limit_pps: 10
gateway_version: Phytec-gw-native-v1.0
buffering_stop_stack: true
log_level: debug  # ("debug", "info", "warning", "error", "critical")
#buffering_max_buffered_packets: 0
#buffering_max_delay_without_publish: 0

