#
#MQTT brocker Settings  
# 
mqtt_hostname: phytecdev.prod-wirepas.com
mqtt_port: 8883
mqtt_username: mosquittouser
mqtt_password: oM4UofPgaARuAPwNCViRpdQ6o0h
mqtt_force_unsecure: false
#
#Gateway settings
#
gateway_id: phytec-gw-imx6ul
gateway_version: Phytec-gw-native-v1.0
#
#Filtering Destination Endpoints
#
whitened_endpoints_filter: "[1-239]"
